clickhouse_imdb:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: sandbox
      host: localhost
      port: 8123
      user: clickadmin
      password: ''
      secure: True
      verify: False
#      cluster: '{cluster}'