clickhouse_imdb:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: imdb_dbt
      host: localhost
      port: 8123
      user: clickadmin
      password: 'aLpjr5HMq'
      secure: False
#      cluster: '{cluster}'