clickhouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: raw
      host: localhost
      port: 8123
      user: clickadmin
      password: 'aLpjr5HMq'
      secure: False
#      cluster: '{cluster}'